name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        env:
          NEXT_TELEMETRY_DISABLED: 1
        run: npm ci
      - name: Run lint (CI)
        run: npm run lint:ci
      - name: Run typecheck
        run: npm run typecheck
      - name: Run tests (CI)
        run: npm run test:ci
      - name: Run production build
        run: npm run build:prod
      - name: Run coverage tests
        run: npm run test:coverage
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage/lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
