name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint:ci
      - name: TypeScript check
        run: npm run typecheck
      - name: Tests
        run: npm run test:ci
      - name: Upload Coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
