name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        env:
          NEXT_TELEMETRY_DISABLED: 1
        run: npm ci
      - name: Prettier (check)
        run: npm run format:check
      - name: Lint
        run: npm run lint:ci
      - name: Type check
        run: npm run typecheck
      - name: Test
        run: npm run test:ci
      - name: Build
        run: npm run build:prod
